if not exists(SELECT name FROM SYS.DATABASES WHERE name = 'SALES')
CREATE DATABASE SALES

USE SALES

if exists(SELECT name FROM sys.objects WHERE name = 'SELL')
DROP TABLE SELL

if exists(SELECT name FROM sys.objects WHERE name = 'COMMODITY')
DROP TABLE COMMODITY


CREATE TABLE COMMODITY
(
NO INT PRIMARY KEY,
NAME CHAR(10) NOT NULL  UNIQUE,
CATEGORY CHAR(10) NOT NULL,
COST FLOAT NOT NULL
)
CREATE TABLE SELL
(
NO INT FOREIGN KEY REFERENCES COMMODITY(NO),
TIME DATETIME NOT NULL,
QUANTITY INT NOT NULL,
PRICE FLOAT NOT NULL,
PROFIT FLOAT 
)

--BACKUP LOG SALES 